name: Deploy bot to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/telegram-weather-bot
            git pull origin master
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart weatherbot
